version: '3.1'

services:
  mongo:
    image: "mongo:4.4"
    container_name: 'MongoDB'
    restart: always
    volumes:
      - volume_mongo:/data/db      
    ports:
      - "27017:27017"
  backend:
    image: "juanpvl/tarea2backend"
    container_name: 'BackendNodeJS'
    restart: always
    ports:
      - "3002:3002"
  frontend:
    image: 'juanpvl/tarea2front'
    container_name: 'frontReact'
    ports:
      - '5173:5173'
volumes:
  volume_mongo: