# Utiliza una imagen base de Alpine con Go ya instalado
FROM golang:alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el código fuente al contenedor
COPY . .

# Compila la aplicación de Go
RUN go build -o main

EXPOSE 3008
# Ejecuta la aplicación al iniciar el contenedor
CMD ["./main"]

#docker build -t jhonathantocay/apiclase5 .
#docker push jhonathantocay/apiclase5 .
#docker build -t jhonathantocay/apiclase5 .